### ISSUE TITLE
npm install ti-mocha fires the install.js file, but doesn't actually set any test harness up 

### ISSUE THREAD

**Issue by Sophrinix** [tonylukasavage/ti-mocha#14]
this might be a bug on my part, but even when I don't have ti-mocha installed globally, and even when I disable node version manager, I am still noticing that when I go inside either a classic or alloy project and npm install ti-mocha, install.js is ran, but nothing is copied into my projects. It doesn't matter if I npm install ti-mocha or npm install ti-mocha@0.1.0

**Comment by Sophrinix** [comment]
it should be noted that when I clone this repository and follow the instructions to run the test, everything passes. 
I mention that because I don't think this is an issue with node being busted.
➜  repos  npm -v
1.3.2

➜  repos  node -v
v0.10.13
again, I've gone back to using npm as provided by titanium studio (and disabled node version manager)

**Comment by tonylukasavage** [comment]
I think I know why this is. Do you by chance have a `node_modules` folder further up your folder hierarchy from your project directory? If you don't have a node_modules folder in your project root, but have one further up the folder hierarchy, npm will install there, throwing off my install script. It's a weird thing npm does so that you can install modules from anywhere inside the current node project.

**Comment by tonylukasavage** [comment]
For more details until I try to address this one, check out the "Cycles, Conflicts, and Folder Parsimony" section for a full explanation of what is likely happening: [https://npmjs.org/doc/files/npm-folders.html](https://npmjs.org/doc/files/npm-folders.html)

## workaround

Make sure you have a `node_modules` folder in your project root, even if its empty

**Comment by tonylukasavage** [comment]
Can you please delete the comments here related to the should.js issue and put them in #13? I don't want to conflate the 2 issues, they are entirely separate. The workaround for this one will have to work for at least the very near future since I looked into the "npm install" process as well as all its environment variables and there doesn't seem to be anything that preserves the directory from which you invoked "npm install", only the directory in which the ti-mocha module is installed, which can't reliably be considered to be "PROJECT/node_modules/ti-mocha" since the absence of a node_modules folder forces it to cycle up the folder hierarchy.

The should.js stuff is still not clear to me. Let's continue the conversation in #13 after you copy over the relevant info.

**Comment by Sophrinix** [comment]
this issue is 100% resolved in terms of ti-mocha behaving strictly as it should. 
I have a node_modules directory in my local project directory. 

Should I be checking in a empty node_modules directory to Github?

**Comment by tonylukasavage** [comment]
No, and that's why I want to leave it open for the time being. I don't want it to be a requirement that you have to have an initial `node_modules` folder. I want it to just work. 

I looked pretty close and I don't see a means of avoiding this with what npm gives me. I'm going to look around a bit more, but I may have to take the plunge and perhaps try to get a PR through in npm if I can find a solid, meaningful use case for knowing the path from which "npm install" was invoked beyond ti-mocha's very specific usage. If I can't find a more generic use case, it's unlikely to be merged even if I did push a PR. In any case, whatever I do take a shot at, I will record here.

**Comment by tonylukasavage** [comment]
`npm install ti-mocha --prefix ./node_modules` will always install to the current directory. I noted this in the README.md as well.
